### ISSUE TITLE
option convert doesn't exist, option obsidian seems to not work

### ISSUE THREAD

**Issue by namtrah** [ebullient/fc5-convert-cli#4]
So I tried to follow your install instructions and it works for the most part (there is a dependency on Mavin `mvnw` which I do not have installed and you do not describe....but that is not important to the real issue.)

tried to run the command 
`fc5-convert convert -o target/reference Collections/CoreRulebooks-merged.xml`

And am getting the error: Unknown option -o. Weirder, the help doesn't give me the "convert" option. I presume it has changed to "obsidian", so I reran the command

`fc5-convert obsidian -o target/reference Collections/CoreRulebooks-merged.xml`

And I receive the following:

💡 Writing files to /mnt/c/Private/DnD/FightClub5e/target/reference
⏱ Reading CoreRulebooksAndSupplements.xml
  ✅ Done.

But I see no file called reference, nor directory, nor nothing. BTW, I am using WSL - Ubuntu 20.04 under Windows.

**Comment by ebullient** [comment]
Yep. `convert` became `obsidian`, because I realized what I was producing wasn't strictly general markdown anymore.

I've just updated the README and pushed some changes supporting custom templates on the command line. Can you try again? I think I've updated the steps to be clearer.

**Comment by namtrah** [comment]
Hi, sorry for the delay. Just tried it again and still no output whatever. is "reference" a file or a directory? Either way I get an OK - Done message but there is nothing output from the command

**Comment by ebullient** [comment]
AH! Ok. I think the trick is making sure you have starting files, and then you construct from there.

So, given you aren't going to rebuild the client (maven would create a target directory) 

The important part is the steps: 

1. Convert a collection into a compendium via a merge operation:
    ```
    fc5-convert transform -o target -x '-merged' FightClub5eXML/Collections/CoreRulebooks.xml
    ```

    This will create a `target/` directory if it doesn't exist, and will create a `CoreRulebooks-merged.xml` file in it that contains the merged content from the resources listed in `FightClub5eXML/Collections/CoreRulebooks.xml`.


2. Convert that compendium to Markdown: 

    ```
    fc5-convert obsidian -o target/reference target/CoreRulebooks-merged.xml
    ```

    This command takes the output from the previous step (`target/CoreRulebooks-merged.xml`) and creates a `target/reference` directory holding .. many? files for the backgrounds, classes, feats, items, monsters, races, and spells described in the XML document.

So this definitely is a two step process: you need to convert some raw collections from the FightClub5eXML repository into a compendium (this is how you select sources), and then convert elements of the compendium into markdown.

**Comment by namtrah** [comment]
Hi! That worked! Yes, it was the "transform" that I was missing out of the documentation. Running this command and then the obsidian (convert) worked well. 

I noticed there are a few issues with tables (especially in the backgrounds), but it is nothing which I would open a bug for. figure it is poor XML on FC5 side.

**Comment by ebullient** [comment]
Let me know what you were expecting... I do a lot of massaging to get tables created correctly. So if you spot something, please open an issue for it!
